### ISSUE TITLE
Unable to create multiple 'baz's at root 'bar'

### ISSUE THREAD

**Issue by alexwasner** [fhfaa/grunt-xmlstoke#2]
I am wanting to automate something like this: `<bar> <baz id="abc"/> <baz id="def"/> </bar>`
Currently, if you write 
           `{ type: 'C', xpath: '/bar/baz', node:'@id', value: 'abc' },`, if baz does not exist, it is not created and if there is a baz with a different id, it overwrites it instead of creating it.

**Comment by fhfaa** [comment]
Pretty much working as intended - but admittedly horrible outside of the use case it was written for. ;p
Maybe using attribute selectors and indexes (see [](https://github.com/fhfaa/grunt-xmlstoke#actionnode-only-insert) ) could work.

Feel free to submit a PR for auto-creating parent nodes.
